import type { Metadata } from "next";
import Image from "next/image";
import { Roboto } from "next/font/google";
import { getCssText } from "@/styles";
import { globalStyles } from "@/styles/global";

import logoImg from "../assets/logo.svg";
import { Container, Header } from "@/styles/pages/app";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Elite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  globalStyles()

  return (
    <html lang="en">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body className={`${roboto.variable}`}>
        <Container>
          <Header>
            <Image src={logoImg.src} alt="Logo" width={120} height={52} />
          </Header>

          {children}
        </Container>

      </body>
    </html>
  );
}
