import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { getCssText } from "@/styles";
import { globalStyles } from "@/styles/global";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Elite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  globalStyles()

  return (
    <html lang="en">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body className={`${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
